# Generated by Django 6.0.5 on 2026-05-23 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_remove_employee_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='created_at',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='created_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Добавлено (Локально)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='created_at_utc',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Добавлено (UTC)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='updated_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Изменено (Локально)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='updated_at_utc',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменено (UTC)'),
        ),
    ]
