# Generated by Django 6.0.5 on 2026-05-23 14:25

import factory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0006_remove_vacancy_created_at_vacancy_created_at_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[factory.models.validate_adult], verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[factory.models.validate_adult], verbose_name='Дата рождения'),
        ),
    ]
