# Generated by Django 6.0.5 on 2026-05-23 16:34

import django.core.validators
import django.db.models.deletion
import factory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_client_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Формат телефона: +375 (29) XXX-XX-XX', regex='^\\+375 \\(\\d{2}\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Формат телефона: +375 (29) XXX-XX-XX', regex='^\\+375 \\(\\d{2}\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factory.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Добавлено (локально)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='updated_at_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Изменено (локально)'),
        ),
        migrations.CreateModel(
            name='FAQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Вопрос')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Отвечено?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос-Ответ',
                'verbose_name_plural': 'Вопросы и ответы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('manager', 'Менеджер'), ('director', 'Директор')], default='client', max_length=20, verbose_name='Роль')),
                ('birth_date', models.DateField(blank=True, null=True, validators=[factory.models.validate_adult], verbose_name='Дата рождения')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Формат телефона: +375 (29) XXX-XX-XX', regex='^\\+375 \\(\\d{2}\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
