# Generated by Django 6.0.5 on 2026-05-24 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0009_employee_user_alter_client_phone_alter_client_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glossaryterm',
            options={'verbose_name': 'Термин (архив)', 'verbose_name_plural': 'Термины (архив, не на сайте)'},
        ),
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factory.promo', verbose_name='Примененный промокод'),
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='is_answered',
            field=models.BooleanField(default=False, verbose_name='Опубликовано на сайте'),
        ),
    ]
