# Generated by Django 6.0.5 on 2026-05-24 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0010_alter_glossaryterm_options_order_promo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factory.promo', verbose_name='Применённый промокод'),
        ),
    ]
