from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('news/', views.news_list, name='news'),
    re_path(r'^news/(?P<pk>\d+)/$', views.news_detail, name='news_detail'),
    path('news/create/', views.article_create, name='article_create'),
    re_path(r'^news/(?P<pk>\d+)/edit/$', views.article_edit, name='article_edit'),
    re_path(r'^news/(?P<pk>\d+)/delete/$', views.article_delete, name='article_delete'),
    path('furniture/', views.furniture_list, name='furniture'),
    re_path(r'^furniture/(?P<pk>\d+)/$', views.furniture_detail, name='furniture_detail'),
    path('furniture/create/', views.furniture_create, name='furniture_create'),
    re_path(r'^furniture/(?P<pk>\d+)/edit/$', views.furniture_edit, name='furniture_edit'),
    re_path(r'^furniture/(?P<pk>\d+)/delete/$', views.furniture_delete, name='furniture_delete'),
    path('orders/', views.order_list, name='orders'),
    re_path(r'^orders/(?P<pk>\d+)/$', views.order_detail, name='order_detail'),
    re_path(r'^orders/(?P<pk>\d+)/edit/$', views.order_edit, name='order_edit'),
    re_path(r'^orders/(?P<pk>\d+)/delete/$', views.order_delete, name='order_delete'),
    re_path(r'^privacy/$', views.privacy, name='privacy'),
    path('clients/', views.client_list, name='clients'),
    path('glossary/', views.glossary, name='glossary'),
    path('glossary/create/', views.glossary_create, name='glossary_create'),
    path('wholesale/', views.wholesale, name='wholesale'),
    path('cart/', views.cart_detail, name='cart_detail'),
    re_path(r'^cart/add/(?P<furniture_id>\d+)/$', views.cart_add, name='cart_add'),
    re_path(r'^cart/remove/(?P<furniture_id>\d+)/$', views.cart_remove, name='cart_remove'),
    path('orders/create/', views.order_create, name='order_create'),
    path('vacancies/', views.vacancies, name='vacancies'),
    path('reviews/', views.reviews, name='reviews'),
    path('promos/', views.promos, name='promos'),
    path('pickup-points/', views.pickup_points, name='pickup_points'),
    path('orders/success/', views.order_success, name='order_success'),
    path('faq/', views.faq_page, name='faq_page'),
    path('contacts/', views.contacts, name='contacts'),
    path('statistics/', views.statistics, name='statistics'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
]
